# Auto-generated by gen-env.sh. Source this before building/running rc2 or
# the plain idris2 binary that isn't run through nix's wrapper script.
export CHEZ="/nix/store/q632qvg9cgf7m8zmw6xsd6nqs5817r1f-chez-scheme-10.4.1/bin/scheme"
export IDRIS2_LIBS="/nix/store/jzzy750hy4l49bpc9383frn0gj6j9lrr-libidris2_support-0.8.0/lib"
export IDRIS2_DATA="/home/hhiroki/projects/idris2-rc-cg/install/idris2-0.8.0/support:/nix/store/jzzy750hy4l49bpc9383frn0gj6j9lrr-libidris2_support-0.8.0/share"
export IDRIS2_PACKAGE_PATH="/home/hhiroki/projects/idris2-rc-cg/install/idris2-0.8.0:/nix/store/9jrvwqm0sa8hyfadasgrr4s8sgbf2qnx-prelude/idris2-0.8.0:/nix/store/lvxqmgy1y632agmhyrask0xhxma9fg92-linear/idris2-0.8.0:/nix/store/9rz5v6awr0avq32gy3x6i3n0gmgmyprb-base/idris2-0.8.0:/nix/store/ldgwa4i0lnrfbqaw9c606ll5fnc03h4s-network/idris2-0.8.0:/nix/store/qcjnhqx2zigc3igaw156lcw03zk2vfdi-contrib/idris2-0.8.0:/nix/store/b3vncplqnp5rzh8z75py27p78gw18fxx-test/idris2-0.8.0"
export LD_LIBRARY_PATH="/nix/store/jzzy750hy4l49bpc9383frn0gj6j9lrr-libidris2_support-0.8.0/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
