#!/usr/bin/env bash
# Regenerates env.sh. Our custom-built idris2-rc2/idris2 executables are
# plain (unwrapped) binaries, invoked via a wrapper script that only sets up
# their own bundled Chez-compiled app dir -- everything else (standard
# packages, data files, native support libraries) they already find on their
# own, self-relatively, under this repo's own install/ prefix. The one thing
# genuinely external is Chez Scheme itself (`scheme`), needed by the Chez
# backend build step (`idris2 --build`) -- extracted here from nixpkgs
# idris2's own wrapped environment, the same way it always was.
set -euo pipefail

OUT="$(dirname "$0")/env.sh"

STRINGS_FILE="$(mktemp)"
trap 'rm -f "$STRINGS_FILE"' EXIT
nix-shell -p idris2 --run 'strings "$(which idris2)"' > "$STRINGS_FILE" 2>/dev/null

CHEZ_PATH="$(grep -- "--set 'CHEZ'" "$STRINGS_FILE" | sed -E "s/.*--set 'CHEZ' '([^']*)'.*/\1/" | head -1)"

RC2_INSTALL_DIR="$(cd "$(dirname "$0")" && pwd)/install/idris2-0.8.0"
RC2_INSTALL_BIN="$(cd "$(dirname "$0")" && pwd)/install/bin"

cat > "$OUT" <<EOF
# Auto-generated by gen-env.sh. Source this before building/running rc2 or
# the plain idris2 binary that isn't run through nix's wrapper script.
export CHEZ="${CHEZ_PATH}"
export LD_LIBRARY_PATH="${RC2_INSTALL_DIR}/lib\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
export PATH="${RC2_INSTALL_BIN}:\$PATH"
EOF

echo "Wrote $OUT"
cat "$OUT"
