#!/usr/bin/env bash
# Regenerates env.sh by extracting nixpkgs idris2's wrapped environment
# (prelude/base/network/contrib/test package paths, libidris2_support, chez)
# from the makeCWrapper invocation embedded in the wrapper binary's strings.
# Our custom-built idris2-rc2 executable is a plain (unwrapped) binary, so it
# needs these same env vars set explicitly to find the standard libraries.
set -euo pipefail

OUT="$(dirname "$0")/env.sh"

nix-shell -p idris2 --run 'strings "$(which idris2)"' > /tmp/idris2-wrapper-strings.$$ 2>/dev/null

extract() {
  local var="$1"
  grep -- "--set '$var'" /tmp/idris2-wrapper-strings.$$ | sed -E "s/.*--set '$var' '([^']*)'.*/\1/" | head -1
}
extract_suffix() {
  local var="$1"
  grep -- "--suffix '$var'" /tmp/idris2-wrapper-strings.$$ | sed -E "s/.*--suffix '$var' ':' '([^']*)'.*/\1/" | head -1
}

CHEZ_PATH="$(extract CHEZ)"
LIBS_PATH="$(extract_suffix IDRIS2_LIBS)"
DATA_PATH="$(extract_suffix IDRIS2_DATA)"
PKG_PATH="$(extract_suffix IDRIS2_PACKAGE_PATH)"

rm -f /tmp/idris2-wrapper-strings.$$

RC2_INSTALL_DIR="$(cd "$(dirname "$0")" && pwd)/install/idris2-0.8.0"

cat > "$OUT" <<EOF
# Auto-generated by gen-env.sh. Source this before building/running rc2 or
# the plain idris2 binary that isn't run through nix's wrapper script.
export CHEZ="${CHEZ_PATH}"
export IDRIS2_LIBS="${LIBS_PATH}"
export IDRIS2_DATA="${RC2_INSTALL_DIR}/support:${DATA_PATH}"
export IDRIS2_PACKAGE_PATH="${RC2_INSTALL_DIR}:${PKG_PATH}"
export LD_LIBRARY_PATH="${LIBS_PATH}\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
EOF

echo "Wrote $OUT"
cat "$OUT"
