#!/usr/bin/env bash
# Regenerates env.sh. Our custom-built idris2-rc2/idris2 executables are
# plain (unwrapped) binaries, invoked via a wrapper script that only sets up
# their own bundled Chez-compiled app dir -- everything else (standard
# packages, data files, native support libraries) they already find on their
# own, self-relatively, under this repo's own install/ prefix. The one thing
# genuinely external is Chez Scheme itself, needed by the Chez backend build
# step (`idris2 --build`): idris2 looks it up on PATH as `scheme` (among other
# names) when CHEZ is unset, so it only has to be installed, not configured.
set -euo pipefail

OUT="$(dirname "$0")/env.sh"

if ! command -v scheme >/dev/null 2>&1; then
    echo "error: no 'scheme' (Chez Scheme) on PATH -- install it first" >&2
    exit 1
fi

RC2_INSTALL_DIR="$(cd "$(dirname "$0")" && pwd)/install/idris2-0.8.0"
RC2_INSTALL_BIN="$(cd "$(dirname "$0")" && pwd)/install/bin"

cat > "$OUT" <<EOF
# Auto-generated by gen-env.sh. Source this before building/running rc2 or
# the plain idris2 binary that isn't run through nix's wrapper script.
export PATH="${RC2_INSTALL_BIN}:\$PATH"
EOF

echo "Wrote $OUT"
cat "$OUT"
