// One-off generator, NOT part of the normal `make` build (see the
// Makefile's own OBJS list -- this file is deliberately absent from
// it). Produces double_convert.c's two lookup tables by exact GMP
// computation rather than hand-copying published constants, so every
// entry is independently reproducible and auditable:
//
//   - `pow5_table.h`: for every integer q in [POW5_QMIN, POW5_QMAX],
//     the correctly-rounded, 128-bit-normalized significand of 5^q --
//     Data.Double.Convert's Eisel-Lemire-style fast parser's table.
//   - `cached_powers.h`: for every integer k in the Grisu2 cached-power
//     grid (step 8, covering the full double exponent range), the
//     correctly-rounded, 64-bit-normalized significand of 10^k --
//     Data.Double.Convert's Grisu2-style fast formatter's table.
//
// Regenerate with:
//   cc -O2 -o /tmp/gen_double_tables gen_double_tables.c -lgmp
//   /tmp/gen_double_tables pow5   > pow5_table.h
//   /tmp/gen_double_tables cached > cached_powers.h
//
#include <gmp.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Both tables need the same underlying computation: the
// correctly-rounded, normalized `nbits`-bit significand M of base^exp
// (exp may be negative), i.e. integers M, E such that
// 2^(nbits-1) <= M < 2^nbits and M * 2^-E is the round-to-nearest
// `nbits`-bit approximation of base^exp. Exact GMP rational arithmetic
// throughout (a shift-and-check loop against the estimated bit length,
// converging in at most one or two iterations since mpz_sizeinbase is
// exact for base 2), so there is no floating-point imprecision
// anywhere in the derivation itself -- only the final `nbits`-bit
// rounding is inherent to what a bounded-width table entry can hold.
static void compute_normalized_pow(long base, long exp, int nbits, mpz_t M_out, long *E_out) {
    mpz_t num, den;
    mpz_inits(num, den, NULL);
    if (exp >= 0) {
        mpz_ui_pow_ui(num, (unsigned long)base, (unsigned long)exp);
        mpz_set_ui(den, 1);
    } else {
        mpz_set_ui(num, 1);
        mpz_ui_pow_ui(den, (unsigned long)base, (unsigned long)(-exp));
    }
    size_t Lnum = mpz_sizeinbase(num, 2);
    size_t Lden = mpz_sizeinbase(den, 2);
    long E = (long)nbits - ((long)Lnum - (long)Lden);

    mpz_t M, rem, shiftedNum, shiftedDen, divisor;
    mpz_inits(M, rem, shiftedNum, shiftedDen, divisor, NULL);

    for (;;) {
        if (E >= 0) {
            mpz_mul_2exp(shiftedNum, num, (mp_bitcnt_t)E);
            mpz_tdiv_qr(M, rem, shiftedNum, den);
            mpz_set(divisor, den);
        } else {
            mpz_mul_2exp(shiftedDen, den, (mp_bitcnt_t)(-E));
            mpz_tdiv_qr(M, rem, num, shiftedDen);
            mpz_set(divisor, shiftedDen);
        }
        long bitsM = (long)mpz_sizeinbase(M, 2);
        if (mpz_sgn(M) == 0) { E += 1; continue; } // exp so negative M truncated to 0 -- need more shift
        if (bitsM < nbits) { E += 1; continue; }
        if (bitsM > nbits) { E -= 1; continue; }
        // bitsM == nbits: round to nearest, ties away from zero (these
        // ratios are never exact ties in practice; the tie rule is
        // inconsequential here).
        mpz_mul_2exp(rem, rem, 1); // 2*rem
        if (mpz_cmp(rem, divisor) >= 0) {
            mpz_add_ui(M, M, 1);
            if ((long)mpz_sizeinbase(M, 2) > nbits) {
                mpz_tdiv_q_2exp(M, M, 1);
                E -= 1;
            }
        }
        break;
    }
    mpz_set(M_out, M);
    *E_out = E;
    mpz_clears(num, den, M, rem, shiftedNum, shiftedDen, divisor, NULL);
}

// Double's full decimal exponent range for a mantissa up to 19 digits
// (matches the well-known Eisel-Lemire table bounds): smallest
// subnormal ~4.9e-324 down to -342 (19-digit mantissa headroom),
// largest finite ~1.8e308 up to 308.
#define POW5_QMIN (-342)
#define POW5_QMAX 308

// Grisu2 cached-power grid: decimal exponents spaced 8 apart (each
// step covers ~26.6 bits of binary exponent, comfortably inside the
// algorithm's usual +-30-ish bit window), wide enough to cover every
// double's binary exponent (subnormal through DBL_MAX).
#define CACHED_KMIN (-348)
#define CACHED_KMAX 340
#define CACHED_STEP 8

static void print_pow5_table(void) {
    printf("// Generated by gen_double_tables.c -- do not hand-edit.\n");
    printf("// Regenerate: cc -O2 -o /tmp/gen_double_tables gen_double_tables.c -lgmp && /tmp/gen_double_tables pow5 > pow5_table.h\n");
    printf("#pragma once\n#include <stdint.h>\n\n");
    printf("#define POW5_QMIN (%d)\n#define POW5_QMAX %d\n\n", POW5_QMIN, POW5_QMAX);
    printf("typedef struct { uint64_t hi, lo; int32_t e; } Pow5Entry;\n\n");
    printf("static const Pow5Entry pow5_table[POW5_QMAX - POW5_QMIN + 1] = {\n");
    mpz_t M, mask64, hi, lo;
    mpz_inits(M, mask64, hi, lo, NULL);
    mpz_ui_pow_ui(mask64, 2, 64);
    mpz_sub_ui(mask64, mask64, 1);
    for (long q = POW5_QMIN; q <= POW5_QMAX; q++) {
        long E;
        compute_normalized_pow(5, q, 128, M, &E);
        mpz_tdiv_q_2exp(hi, M, 64);
        mpz_and(lo, M, mask64);
        unsigned long hi_ul = mpz_get_ui(hi);
        unsigned long lo_ul = mpz_get_ui(lo);
        printf("  { 0x%016lxULL, 0x%016lxULL, %ld }, /* q=%ld */\n", hi_ul, lo_ul, E, q);
    }
    printf("};\n");
    mpz_clears(M, mask64, hi, lo, NULL);
}

static void print_cached_powers(void) {
    printf("// Generated by gen_double_tables.c -- do not hand-edit.\n");
    printf("// Regenerate: cc -O2 -o /tmp/gen_double_tables gen_double_tables.c -lgmp && /tmp/gen_double_tables cached > cached_powers.h\n");
    printf("#pragma once\n#include <stdint.h>\n\n");
    printf("#define CACHED_KMIN (%d)\n#define CACHED_KMAX %d\n#define CACHED_STEP %d\n\n", CACHED_KMIN, CACHED_KMAX, CACHED_STEP);
    printf("typedef struct { uint64_t f; int32_t e; int32_t dk; } CachedPower;\n\n");
    int n = (CACHED_KMAX - CACHED_KMIN) / CACHED_STEP + 1;
    printf("#define CACHED_POWERS_COUNT %d\n", n);
    printf("static const CachedPower cached_powers[CACHED_POWERS_COUNT] = {\n");
    mpz_t M;
    mpz_init(M);
    for (long k = CACHED_KMIN; k <= CACHED_KMAX; k += CACHED_STEP) {
        long E;
        compute_normalized_pow(10, k, 64, M, &E);
        unsigned long f_ul = mpz_get_ui(M);
        printf("  { 0x%016lxULL, %ld, %ld },\n", f_ul, E, k);
    }
    printf("};\n");
    mpz_clear(M);
}

int main(int argc, char **argv) {
    if (argc != 2) { fprintf(stderr, "usage: %s pow5|cached\n", argv[0]); return 1; }
    if (strcmp(argv[1], "pow5") == 0) print_pow5_table();
    else if (strcmp(argv[1], "cached") == 0) print_cached_powers();
    else { fprintf(stderr, "unknown table: %s\n", argv[1]); return 1; }
    return 0;
}
